use anchor_lang::prelude::*;
use arcium_anchor::prelude::*;
use crate::errors::ErrorCode;
use crate::states::*;
use crate::instructions::*;
use crate::COMP_DEF_OFFSET_MATCH_ORDERS;
use crate::SignerAccount;
use arcium_client::idl::arcium::types::CallbackAccount;

const GLOBAL_ORDERBOOK_SEED: &[u8] = b"global_orderbook";
use crate::ID;
use crate::ID_CONST;

pub fn trigger_matching(
    ctx: Context<TriggerMatching>,
    computation_offset: u64,
) -> Result<()> {
    let global_orderbook = &mut ctx.accounts.global_orderbook;
    let current_time = Clock::get()?.unix_timestamp;
    
    // Rate limit matching (every 15 seconds) or based on complex logic based on filling of the orderbook
    require!(
        current_time >= global_orderbook.last_match_timestamp + 15,
        ErrorCode::MatchingTooFrequent
    );

    global_orderbook.last_match_timestamp = current_time;

    let args = vec![
        // Backend user (Shared) - To receive encrypted match results
        Argument::ArcisPubkey(global_orderbook.backend_pubkey),
        Argument::PlaintextU128(0),  // Fresh nonce for this match batch (generated by MXE)
        
        // OrderBook (Enc<Mxe, OrderBook>)
        Argument::PlaintextU128(global_orderbook.orderbook_nonce),
        Argument::Account(
            global_orderbook.key(),
            8 + 32,  
            1302
        ),
    ];

    ctx.accounts.sign_pda_account.bump = ctx.bumps.sign_pda_account;

    queue_computation(
        ctx.accounts,
        computation_offset,
        args,
        None,
        vec![SubmitOrderCallback::callback_ix(&[
            CallbackAccount {
                pubkey: ctx.accounts.global_orderbook.key(),
                is_writable: true,
            }
        ])],
    )?;

    msg!("Matching triggered. Computation offset: {}", computation_offset);

    Ok(())
}

#[queue_computation_accounts("match_orders", payer)]
#[derive(Accounts)]
#[instruction(computation_offset: u64)]
pub struct TriggerMatching<'info> {
    #[account(mut)]
    pub payer: Signer<'info>,
    #[account(
        init_if_needed,
        space = 9,
        payer = payer,
        seeds = [&SIGN_PDA_SEED],
        bump,
        address = derive_sign_pda!(),
    )]
    pub sign_pda_account: Account<'info, SignerAccount>,
    #[account(address = derive_mxe_pda!())]
    pub mxe_account: Account<'info, MXEAccount>,
    #[account(mut, address = derive_mempool_pda!())]
    /// CHECK: mempool_account, checked by the arcium program.
    pub mempool_account: UncheckedAccount<'info>,
    #[account(mut, address = derive_execpool_pda!())]
    /// CHECK: executing_pool, checked by the arcium program.
    pub executing_pool: UncheckedAccount<'info>,
    #[account(mut, address = derive_comp_pda!(computation_offset))]
    /// CHECK: computation_account, checked by the arcium program.
    pub computation_account: UncheckedAccount<'info>,
    #[account(address = derive_comp_def_pda!(COMP_DEF_OFFSET_MATCH_ORDERS))]
    pub comp_def_account: Account<'info, ComputationDefinitionAccount>,
    #[account(mut, address = derive_cluster_pda!(mxe_account))]
    pub cluster_account: Account<'info, Cluster>,
    #[account(mut, address = ARCIUM_FEE_POOL_ACCOUNT_ADDRESS)]
    pub pool_account: Account<'info, FeePool>,
    #[account(address = ARCIUM_CLOCK_ACCOUNT_ADDRESS)]
    pub clock_account: Account<'info, ClockAccount>,
    pub system_program: Program<'info, System>,
    pub arcium_program: Program<'info, Arcium>,
    #[account(
        mut,
        seeds = [GLOBAL_ORDERBOOK_SEED],
        bump = global_orderbook.bump,
    )]
    pub global_orderbook: Account<'info, GlobalOrderBookState>,
}

#[event]
pub struct MatchingTriggeredEvent {
    pub computation_offset: u64,
    pub timestamp: i64,
    pub orderbook_nonce: u128,
}