[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
matching_engine = "DQ5MR2aPD9sPBN9ukVkhwrAn8ADxpkAE5AHUnXxKEvn1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts --ignore tests/helpers/**/*.ts"

[test.validator]
[[test.genesis]]
address = "BKck65TgoKRokMjQM3datB9oRwJ8rAj2jxPXvHXUvcL6"
program = "/Users/arnabnandi/matching_engine/artifacts/arcium_program_0.3.0.so"

[[test.validator.account]]
address = "FHriyvoZotYiFnbUzKFjzRSb2NiaC8RPWY7jtKuKhg65"
filename = "artifacts/arcium_clock.json"

[[test.validator.account]]
address = "7MGSS4iKNM4sVib7bDZDJhVqB6EcchPwVnTKenCY1jt3"
filename = "artifacts/arcium_fee_pool.json"

[[test.validator.account]]
address = "BoVUVSJAhob2cvM5z4JZTdS6VWRSznh3bbzQD1TFjvDP"
filename = "artifacts/arx_mint.json"

[[test.validator.account]]
address = "Hoamid9gD8dEgLrirgt3gNnAWhmxYe5LSKrJJUGGd4DA"
filename = "artifacts/wallet_acc_Hoam_d4DA.json"

[[test.validator.account]]
address = "6GoLznkMwocY3f2D7fTZS77tx3n8bt65oc1z7YLvgAYd"
filename = "artifacts/arx_ata_Hoam_d4DA.json"

[[test.validator.account]]
address = "4rdhhkdji2JpMFL3KrTzZrQkmTcWeWNdWeEwvtQHtxE2"
filename = "artifacts/wallet_acc_4rdh_txE2.json"

[[test.validator.account]]
address = "34TNE23ULx7eyhg4n8v7E5reVk6xqWZ7hHFdT4xzZgit"
filename = "artifacts/wallet_acc_callback_34TN_Zgit.json"

[[test.validator.account]]
address = "Dgn5L3eancHtpKhJQ9kJsbkAprJgcQNT1WKfXYvuQh3m"
filename = "artifacts/arx_ata_4rdh_txE2.json"

[[test.validator.account]]
address = "GM4ipSopx99934UEdR8egSmdkz7RAW5GxTJp5gQgkkKg"
filename = "artifacts/operator_acc_4rdh_txE2.json"

[[test.validator.account]]
address = "ELoRR19zrps1G3UYKcAxr7LKbw3kbqkVUXVY9dETMWN7"
filename = "artifacts/arx_node_4rdh_txE2.json"

[[test.validator.account]]
address = "D3oUVoE4aBCptzCvHmBnvwXaJmAvVHum9Qrc7YjBamV"
filename = "artifacts/wallet_acc_D3oU_BamV.json"

[[test.validator.account]]
address = "FLNQwki5Zehh7WgttTjxwLmE1nbj8vq1nueZzBhnYprH"
filename = "artifacts/wallet_acc_callback_FLNQ_YprH.json"

[[test.validator.account]]
address = "CqTkjwioEqmLzUpLC37fvo7hTrgGnb7btRrWtb15mw38"
filename = "artifacts/arx_ata_D3oU_BamV.json"

[[test.validator.account]]
address = "6kfdQwQWi3Sx4w94846PneLpdD2wYAq6zvTfgbu8d6Hk"
filename = "artifacts/operator_acc_D3oU_BamV.json"

[[test.validator.account]]
address = "XdfSwb8ZajhN7CerfBSJVhyfx5fyLtv34QVKSRgMFA9"
filename = "artifacts/arx_node_D3oU_BamV.json"

[[test.validator.account]]
address = "GgSqqAyH7AVY3Umcv8NvncrjFaNJuQLmxzxFxPoPW2Yd"
filename = "artifacts/cluster_acc_0.json"

[[test.validator.account]]
address = "4kJ3UjPERsQMfRGKup3xEab31fmUmC9wYutEsfQ11M9d"
filename = "artifacts/submit_order_raw_circuit_0.json"

[[test.validator.account]]
address = "AKTUDcfmSPpFCLjP8kq21VwMgekCu1HRuxNkWRRZfVDF"
filename = "artifacts/init_order_book_raw_circuit_0.json"

[[test.validator.account]]
address = "ETbvx2iQmqCgsAsdie6Akk3nJ85J6Jpj1YMyvbAjW4wo"
filename = "artifacts/match_orders_raw_circuit_0.json"

[[test.validator.account]]
address = "HgqUtdz7PSmoryL6RhuFdzzRnDc9EoA62L8HTV6nSL9m"
filename = "artifacts/mxe_keygen_comp_def.json"

[[test.validator.account]]
address = "HGo4rueAiEorERTGtr1KQbHAUKmLcukCdmkTwsVXyk3P"
filename = "artifacts/mxe_keygen_comp.json"

[[test.validator.account]]
address = "A9czbBrdGqSVgWt2Y7x24jyTFJaaCMPpAP9SzTWbQYVR"
filename = "artifacts/mxe_acc.json"

[[test.validator.account]]
address = "2mxFUd3ri6nrFZqGLQvamUW57rABaHXedqJsTAHjLqCW"
filename = "artifacts/mempool_acc.json"

[[test.validator.account]]
address = "6LBjtQoLwKHJg8kJqYMjivRGSRq79GBkC2QaHq2ZTeQr"
filename = "artifacts/executing_pool_acc.json"
