[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
matching_engine = "DQ5MR2aPD9sPBN9ukVkhwrAn8ADxpkAE5AHUnXxKEvn1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts --ignore tests/helpers/**/*.ts"

[test.validator]
[[test.genesis]]
address = "BKck65TgoKRokMjQM3datB9oRwJ8rAj2jxPXvHXUvcL6"
program = "/Users/arnabnandi/matching_engine/artifacts/arcium_program_0.3.0.so"

[[test.validator.account]]
address = "FHriyvoZotYiFnbUzKFjzRSb2NiaC8RPWY7jtKuKhg65"
filename = "artifacts/arcium_clock.json"

[[test.validator.account]]
address = "7MGSS4iKNM4sVib7bDZDJhVqB6EcchPwVnTKenCY1jt3"
filename = "artifacts/arcium_fee_pool.json"

[[test.validator.account]]
address = "BoVUVSJAhob2cvM5z4JZTdS6VWRSznh3bbzQD1TFjvDP"
filename = "artifacts/arx_mint.json"

[[test.validator.account]]
address = "Hoamid9gD8dEgLrirgt3gNnAWhmxYe5LSKrJJUGGd4DA"
filename = "artifacts/wallet_acc_Hoam_d4DA.json"

[[test.validator.account]]
address = "6GoLznkMwocY3f2D7fTZS77tx3n8bt65oc1z7YLvgAYd"
filename = "artifacts/arx_ata_Hoam_d4DA.json"

[[test.validator.account]]
address = "J1ZgW5quWB6thf4bbLPR3EbPrQM5TzZMUGdBZNrxFYDa"
filename = "artifacts/wallet_acc_J1Zg_FYDa.json"

[[test.validator.account]]
address = "DFzuH7FUxgTJbtfpfycZAiAxU3xVmDpLYakmUbaE38ex"
filename = "artifacts/wallet_acc_callback_DFzu_38ex.json"

[[test.validator.account]]
address = "77WzMWzgCandcquWjA6qiWs2gBvULSna7xAaXGxgSfcn"
filename = "artifacts/arx_ata_J1Zg_FYDa.json"

[[test.validator.account]]
address = "Cb5DvACHoWkQ6apdYHdfGRkTYbWzeEhRLn6UwjiRUr5s"
filename = "artifacts/operator_acc_J1Zg_FYDa.json"

[[test.validator.account]]
address = "ELoRR19zrps1G3UYKcAxr7LKbw3kbqkVUXVY9dETMWN7"
filename = "artifacts/arx_node_J1Zg_FYDa.json"

[[test.validator.account]]
address = "CexcKqSY9USZhGW81xKi34iHCUwS4FLrmbvoFEbanCbZ"
filename = "artifacts/wallet_acc_Cexc_nCbZ.json"

[[test.validator.account]]
address = "3MZPYGR5a3duSXKudAJSQCLhtNHnvhFwfESMb38CwPU4"
filename = "artifacts/wallet_acc_callback_3MZP_wPU4.json"

[[test.validator.account]]
address = "SmLUyP1B7pz1sZcKhowGbWd7EkTJU3RXF1WL4hAWRY4"
filename = "artifacts/arx_ata_Cexc_nCbZ.json"

[[test.validator.account]]
address = "Byp9TMYJGwQyuonhKGbpNtWEJVFuMV3nfJLeMEVTq4fx"
filename = "artifacts/operator_acc_Cexc_nCbZ.json"

[[test.validator.account]]
address = "XdfSwb8ZajhN7CerfBSJVhyfx5fyLtv34QVKSRgMFA9"
filename = "artifacts/arx_node_Cexc_nCbZ.json"

[[test.validator.account]]
address = "GgSqqAyH7AVY3Umcv8NvncrjFaNJuQLmxzxFxPoPW2Yd"
filename = "artifacts/cluster_acc_0.json"

[[test.validator.account]]
address = "4kJ3UjPERsQMfRGKup3xEab31fmUmC9wYutEsfQ11M9d"
filename = "artifacts/submit_order_raw_circuit_0.json"

[[test.validator.account]]
address = "H88Yw3dKWGcpJAS3Dg59QGjGrNZGeDsXmc17oUs4EV4p"
filename = "artifacts/submit_order_raw_circuit_1.json"

[[test.validator.account]]
address = "AKTUDcfmSPpFCLjP8kq21VwMgekCu1HRuxNkWRRZfVDF"
filename = "artifacts/init_order_book_raw_circuit_0.json"

[[test.validator.account]]
address = "ETbvx2iQmqCgsAsdie6Akk3nJ85J6Jpj1YMyvbAjW4wo"
filename = "artifacts/match_orders_raw_circuit_0.json"

[[test.validator.account]]
address = "4FPPmM88XnUHPyJ2xMHt3VawSZocaGtiR5TWUfXDJTQv"
filename = "artifacts/match_orders_raw_circuit_1.json"

[[test.validator.account]]
address = "5XXutiJxW7sm7pVW9xQ5eisWjsMb1hJHte3FEmHkUsKd"
filename = "artifacts/match_orders_raw_circuit_2.json"

[[test.validator.account]]
address = "FJ3V3t153p24bHZ1RK9HfyvgahqW4GgGAbeLdnhKhVQs"
filename = "artifacts/match_orders_raw_circuit_3.json"

[[test.validator.account]]
address = "68gYk2i7kHaMbaoWc295oZwMGcpZWrijiHhyeyk1H1UD"
filename = "artifacts/match_orders_raw_circuit_4.json"

[[test.validator.account]]
address = "BaQW7TPmgAt2afzPMNziaJL1c8gbGpQeZZumFs6HHQjC"
filename = "artifacts/match_orders_raw_circuit_5.json"

[[test.validator.account]]
address = "8y5mBNVR7pyGqMNW47t18G4Mfupie1fgTo6N4g4cGUfo"
filename = "artifacts/match_orders_raw_circuit_6.json"

[[test.validator.account]]
address = "HgqUtdz7PSmoryL6RhuFdzzRnDc9EoA62L8HTV6nSL9m"
filename = "artifacts/mxe_keygen_comp_def.json"

[[test.validator.account]]
address = "HGo4rueAiEorERTGtr1KQbHAUKmLcukCdmkTwsVXyk3P"
filename = "artifacts/mxe_keygen_comp.json"

[[test.validator.account]]
address = "A9czbBrdGqSVgWt2Y7x24jyTFJaaCMPpAP9SzTWbQYVR"
filename = "artifacts/mxe_acc.json"

[[test.validator.account]]
address = "2mxFUd3ri6nrFZqGLQvamUW57rABaHXedqJsTAHjLqCW"
filename = "artifacts/mempool_acc.json"

[[test.validator.account]]
address = "6LBjtQoLwKHJg8kJqYMjivRGSRq79GBkC2QaHq2ZTeQr"
filename = "artifacts/executing_pool_acc.json"
